export const topShipDeals = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/4201245/pexels-photo-4201245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    shipName: "Aurora Voyager",
    type: "Cargo",
    producer: "Neptune Shipyards",
    price: "5,600",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/327090/pexels-photo-327090.jpeg?auto=compress&cs=tinysrgb&w=1600",
    shipName: "Stellar Explorer",
    type: "Cruiser",
    producer: "Orion Marine",
    price: "4,850",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/276525/pexels-photo-276525.jpeg?auto=compress&cs=tinysrgb&w=1600",
    shipName: "Oceanic Titan",
    type: "Tanker",
    producer: "Poseidon Works",
    price: "6,720",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/1739522/pexels-photo-1739522.jpeg?auto=compress&cs=tinysrgb&w=1600",
    shipName: "Neptune Star",
    type: "Yacht",
    producer: "Aqua Dynamics",
    price: "3,950",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/1917425/pexels-photo-1917425.jpeg?auto=compress&cs=tinysrgb&w=1600",
    shipName: "Celestial Wave",
    type: "Cargo",
    producer: "Atlas Shipbuilders",
    price: "5,230",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg?auto=compress&cs=tinysrgb&w=1600",
    shipName: "Poseidon Legacy",
    type: "Cruiser",
    producer: "Neptune Shipyards",
    price: "4,110",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/4061428/pexels-photo-4061428.jpeg?auto=compress&cs=tinysrgb&w=1600",
    shipName: "Mariner's Glory",
    type: "Yacht",
    producer: "Aqua Dynamics",
    price: "3,760",
  },
];
